language: python
sudo: false
cache: pip

matrix:
  include:
    - python: 3.5
      env: TOXENV=py35
    - python: 3.5-dev
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=ALL
    - python: 3.6-dev
      env: TOXENV=ALL
    - python: pypy3
      env: TOXENV=ALL

notifications:
  email:
    recipients:
      - jtonye@ymail.com

env:
  - DJANGO_SETTINGS_MODULE=django_view_breadcrumbs.settings

install:
  - make install-test

script:
  - tox

addons:
  apt:
    update: true
    sources:
      - travis-ci/sqlite3
    packages:
      - sqlite3
