name: automerge
on:
  check_suite:
    types:
      - completed

jobs:
  cleanup-runs:
    runs-on: ubuntu-latest
    if: |
      (
        github.actor == 'dependabot[bot]' ||
        github.actor == 'dependabot' ||
        github.actor == 'dependabot-preview[bot]' ||
        github.actor == 'dependabot-preview' ||
        github.actor == 'renovate[bot]' ||
        github.actor == 'renovate'
      )
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@v0.3.3
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
  
  automerge:
    runs-on: ubuntu-latest
    if: |
      (
        github.actor == 'dependabot[bot]' ||
        github.actor == 'dependabot' ||
        github.actor == 'dependabot-preview[bot]' ||
        github.actor == 'dependabot-preview' ||
        github.actor == 'renovate[bot]' ||
        github.actor == 'renovate'
      )
    steps:
      - name: automerge
        uses: pascalgn/automerge-action@v0.14.3
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          MERGE_METHOD: "rebase"
          UPDATE_METHOD: "rebase"
          MERGE_RETRIES: "10"
          MERGE_RETRY_SLEEP: "100000"
          MERGE_LABELS: ""
